# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Features.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(403, 684)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 400, 680))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(400, 680))
        self.frame_3.setMaximumSize(QtCore.QSize(400, 680))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"border: 1px solid black;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setContentsMargins(-1, 3, 7, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("border-radius: initial;\n"
"border:initial;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/new_icons/1486395882-close_80604.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2, 0, QtCore.Qt.AlignRight)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(400, 0))
        self.label_2.setStyleSheet("font: 13pt \"Arial\";")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(370, 0))
        self.frame.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame.setStyleSheet("border-radius: 10px;\n"
"padding: 10px;\n"
"border:initial;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_12 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_12.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_12.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_12.setStyleSheet("QCheckBox {border: 1px solid black;\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    ;\n"
"    background-color: rgb(0, 185, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout.addWidget(self.checkBox_12, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(40, 1, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 12pt \"Arial\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.scrollArea = QtWidgets.QScrollArea(self.frame)
        self.scrollArea.setMinimumSize(QtCore.QSize(360, 440))
        self.scrollArea.setStyleSheet("QScrollBar::vertical{\n"
"    border:none;\n"
"    background-color: rgba(0,0,0,0.1);\n"
"}\n"
"\n"
"QCheckBox {border: 1px solid black;\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    ;\n"
"    background-color: rgb(0, 185, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -216, 323, 636))
        self.scrollAreaWidgetContents_2.setStyleSheet("QScrollBar::vertical{\n"
"    border:none;\n"
"    background-color: rgba(0,0,0,0.4);\n"
"}\n"
"")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_21 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_21.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_21.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_21.setStyleSheet("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout_2.addWidget(self.checkBox_21, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_20 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_20.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_20.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_20.setStyleSheet("")
        self.checkBox_20.setObjectName("checkBox_20")
        self.verticalLayout_2.addWidget(self.checkBox_20, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_19 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_19.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_19.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_19.setStyleSheet("")
        self.checkBox_19.setObjectName("checkBox_19")
        self.verticalLayout_2.addWidget(self.checkBox_19, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_18 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_18.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_18.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_18.setStyleSheet("")
        self.checkBox_18.setObjectName("checkBox_18")
        self.verticalLayout_2.addWidget(self.checkBox_18, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_16 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_16.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_16.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_16.setStyleSheet("")
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_2.addWidget(self.checkBox_16, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_15 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_15.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_15.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_15.setStyleSheet("")
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_2.addWidget(self.checkBox_15, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_14 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_14.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_14.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_14.setStyleSheet("")
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_2.addWidget(self.checkBox_14, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_7 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_7.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_7.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_7.setStyleSheet("")
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_2.addWidget(self.checkBox_7, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_5.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_5.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_5.setStyleSheet("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_2.addWidget(self.checkBox_5, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_8 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_8.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_8.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_8.setStyleSheet("")
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_2.addWidget(self.checkBox_8, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_11 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_11.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_11.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_11.setStyleSheet("QCheckBox {border: 1px solid black;\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    ;\n"
"    background-color: rgb(0, 185, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_2.addWidget(self.checkBox_11, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_6.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_6.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_6.setStyleSheet("QCheckBox {border: 1px solid black;\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    ;\n"
"    background-color: rgb(0, 185, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_2.addWidget(self.checkBox_6, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_9 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_9.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_9.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_9.setStyleSheet("QCheckBox {border: 1px solid black;\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    ;\n"
"    background-color: rgb(0, 185, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_2.addWidget(self.checkBox_9, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_17 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_17.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_17.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_17.setStyleSheet("QCheckBox {border: 1px solid black;\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    ;\n"
"    background-color: rgb(0, 185, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.checkBox_17.setObjectName("checkBox_17")
        self.verticalLayout_2.addWidget(self.checkBox_17, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_13 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_13.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_13.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_13.setStyleSheet("QCheckBox {border: 1px solid black;\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    ;\n"
"    background-color: rgb(0, 185, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_2.addWidget(self.checkBox_13)
        self.checkBox_22 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        self.checkBox_22.setMinimumSize(QtCore.QSize(300, 33))
        self.checkBox_22.setMaximumSize(QtCore.QSize(300, 33))
        self.checkBox_22.setStyleSheet("QCheckBox {border: 1px solid black;\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    ;\n"
"    background-color: rgb(0, 185, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_2.addWidget(self.checkBox_22)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("QPushButton {\n"
"border: 1px solid black;\n"
"background-color: rgba(0,0,0,0.2);\n"
"padding: 7px;\n"
"border-radius: 6px;\n"
"font: 11pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(0,0,0,0.4);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(0,0,0,0);\n"
"}")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/new_icons/free-icon-arrow-point-to-right-32213.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Выберите признаки, которые влияют на выставляемую оценку:"))
        self.checkBox_12.setText(_translate("Form", "Использовать все"))
        self.label.setText(_translate("Form", "ИЛИ"))
        self.checkBox_21.setText(_translate("Form", "Год выхода"))
        self.checkBox_20.setText(_translate("Form", "Средняя оценка на Кинопоиске"))
        self.checkBox_19.setText(_translate("Form", "Количество оценок на Кинопоиске"))
        self.checkBox_18.setText(_translate("Form", "Средняя оценка на IMDb"))
        self.checkBox_16.setText(_translate("Form", "Количество оценок на IMDb"))
        self.checkBox_15.setText(_translate("Form", "Оценка критиков"))
        self.checkBox_14.setText(_translate("Form", "Количество оценок критиков"))
        self.checkBox_7.setText(_translate("Form", "Продолжительность"))
        self.checkBox_5.setText(_translate("Form", "Количество премий Оскар"))
        self.checkBox_8.setText(_translate("Form", "Количество номинаций на Оскар"))
        self.checkBox_11.setText(_translate("Form", "Количество других премий"))
        self.checkBox_6.setText(_translate("Form", "Количество других номинаций"))
        self.checkBox_9.setText(_translate("Form", "Входит в ТОП250 IMDB"))
        self.checkBox_17.setText(_translate("Form", "Десятилетие выхода"))
        self.checkBox_13.setText(_translate("Form", "Жанры"))
        self.checkBox_22.setText(_translate("Form", "Страны"))
import new_icons


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
